version: '3.9'
services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/c:latest
    restart: unless-stopped
    volumes:
      - ./pds:/pds
      - ./data:/data
      - ./blobstore:/app/blobstore
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # SMTP Configuration for Resend
      - PDS_EMAIL_SMTP_URL=smtps://${SMTP_USER}:${SMTP_PASS}@${SMTP_HOST}:${SMTP_PORT}/
      - PDS_EMAIL_FROM_ADDRESS=${SMTP_FROM}
      # Disk Blobstore Configuration
      - PDS_BLOBSTORE_DISK_LOCATION=/app/blobstore
      - PDS_BLOBSTORE_DISK_TMP_LOCATION=/app/blobstore/tmp
      # PLC Configuration
      - PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=${PLC_ROTATION_KEY}
    networks:
      - shared_network
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/xrpc/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: pds-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-main.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pds
    networks:
      - shared_network

networks:
  shared_network:
    external: true 